---
title: "Report"
author:
- familyname: Wang
  othernames: Yiru
  address: Monash Universtidy
  email: "ywan0553@student.monash.edu"
  correspondingauthor: true
  qualifications: section1
- familyname: Xu
  othernames: Kexin
  address: Monash University
  email: "kxuu0029@student.monash.edu"
  qualifications: section2
  correspondingauthor: true
- familyname: Tang
  othernames: Ruiqi
  address: Monash University
  email: "rtan00062student.monash.edu"
  correspondingauthor: true
  qualifications: section3
department: Our consultancy \newline Yiru Wang &\newline Kexin XU &\newline Ruiqi Tang
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
header-includes:
 \usepackage{float}
 \floatplacement{figure}{H}
 \floatplacement{table}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", out.width = "50%")
```



```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries
library(tinytex)
library(gridExtra)
library(tidyverse)
library(readr)
library(bookdown)
library(knitr)
library(readabs)
library(readxl)
```

```{r, message=FALSE}
Homicide <- read_excel("data/Victims_of_Crime_Australia.xls", 
    sheet = "Table 2", range = anchored("A20", dim = c(6,11))) 
colnames(Homicide) <- c("age" ,2010, 2011, 2012, 2013,	2014,	2015,	2016,	2017,	2018,	2019)

Murder <- read_excel("data/Victims_of_Crime_Australia.xls", 
    sheet = "Table 2", range = anchored("A39", dim = c(6,11)))
colnames(Murder) <- c("age" ,2010, 2011, 2012, 2013,	2014,	2015,	2016,	2017,	2018,	2019)

Attempted_murder <- read_excel("data/Victims_of_Crime_Australia.xls", 
    sheet = "Table 2", range = anchored("A58", dim = c(6,11))) 

colnames(Attempted_murder) <- c("age" ,2010, 2011, 2012, 2013,	2014,	2015,	2016,	2017,	2018,	2019)

Manslaughter <-  read_excel("data/Victims_of_Crime_Australia.xls", 
    sheet = "Table 2", range = anchored("A77", dim = c(6,11)))

colnames(Manslaughter) <- c("age" ,2010, 2011, 2012, 2013,	2014,	2015,	2016,	2017,	2018,	2019)

Sexual_assault <- read_excel("data/Victims_of_Crime_Australia.xls", 
    sheet = "Table 2", range = anchored("A106", dim = c(10,11)))

colnames(Sexual_assault) <- c("age" ,2010, 2011, 2012, 2013,	2014,	2015,	2016,	2017,	2018,	2019)

Kidnapping_abduction <-  read_excel("data/Victims_of_Crime_Australia.xls", 
    sheet = "Table 2", range = anchored("A138", dim = c(9,11)))

colnames(Kidnapping_abduction) <- c("age" ,2010, 2011, 2012, 2013,	2014,	2015,	2016,	2017,	2018,	2019)

Robbery <- read_excel("data/Victims_of_Crime_Australia.xls", 
    sheet = "Table 2", range = anchored("A171", dim = c(10,11)))

colnames(Robbery) <- c("age" ,2010, 2011, 2012, 2013,	2014,	2015,	2016,	2017,	2018,	2019)

Armed_robbery <- read_excel("data/Victims_of_Crime_Australia.xls", 
    sheet = "Table 2", range = anchored("A205", dim = c(10,11)))

colnames(Armed_robbery) <- c("age" ,2010, 2011, 2012, 2013,	2014,	2015,	2016,	2017,	2018,	2019)

Unarmed_robbery <- read_excel("data/Victims_of_Crime_Australia.xls", 
    sheet = "Table 2", range = anchored("A239", dim = c(10,11)))

colnames(Unarmed_robbery) <- c("age" ,2010, 2011, 2012, 2013,	2014,	2015,	2016,	2017,	2018,	2019)

Blackmail_extortion <- read_excel("data/Victims_of_Crime_Australia.xls", 
    sheet = "Table 2", range = anchored("A271", dim = c(9,11)))

colnames(Blackmail_extortion) <- c("age" ,2010, 2011, 2012, 2013,	2014,	2015,	2016,	2017,	2018,	2019)

```


```{r}
Homicide %>%
 pivot_longer(cols = '2010':'2019',  
                names_to = "Year",            
                values_to = "Count") -> homicide_long

homicide_long %>%
  pivot_wider(id_cols = c(age, Year, Count), names_from = age, values_from = Count) %>%
  mutate(Year = as_factor(Year)) %>%
  mutate(class = "Homicide") -> homicide_wider



homicide_long %>%
  group_by(age) %>%
  summarise(sum = sum(Count)) %>%
  mutate(class = "Homicide") %>%
  filter(age != "Total") -> homicide_age
```

```{r}
Attempted_murder %>%
  pivot_longer(cols = '2010':'2019',  
                names_to = "Year",            
                values_to = "Count") -> AM_longer

AM_longer %>%
  pivot_wider(id_cols = c(age, Year, Count), names_from = age, values_from = Count) %>%
  mutate(Year = as_factor(Year)) %>%
  mutate(class = "Attempted_murder") -> AM_wider

AM_longer %>%
  group_by(age) %>%
  summarise(sum = sum(Count)) %>%
  mutate(class = "Attempted_murder") %>%
  filter(age != "Total") -> am_age
```


```{r}
Robbery %>%
   pivot_longer(cols = '2010':'2019',  
                names_to = "Year",            
                values_to = "Count") -> Robbery_longer

Robbery_longer %>%
  pivot_wider(id_cols = c(age, Year, Count), names_from = age, values_from = Count) %>%
  mutate(Year = as_factor(Year)) %>%
  mutate(class = "robbery") -> Robbery_wider

Robbery_longer %>%
  group_by(age) %>%
  summarise(sum = sum(Count)) %>%
  mutate(class = "robbery") %>%
  filter(age != "Total") -> robbery_age
```

```{r}
Kidnapping_abduction %>%
  pivot_longer(cols = '2010':'2019',  
                names_to = "Year",            
                values_to = "Count") -> ka_longer

ka_longer %>%
  group_by(age) %>%
  summarise(sum = sum(Count)) %>%
  mutate(class = "abduction") %>%
  filter(age != "Total") -> ka_age
```


```{r}
homicide_age %>%
 full_join(robbery_age, key = age, by = c("age", "sum", "class"))%>%
 full_join(ka_age, key = age, by = c("age", "sum", "class")) -> data

data %>%
  ggplot() + geom_col(aes(x= class, y = sum, fill = age))
```

```{r}
homicide_wider %>% 
  right_join(Robbery_wider, key = year) %>%
  ggplot() + geom_line(aes(aes(x = Year, y = Total, colours = class)))
```

```{r}
Attempted_murder
```


\section*{State}


\section*{Gender}


\section*{Age}


