---
title: "Report"
author:
- familyname: Wang
  othernames: Yiru
  address: Monash Universtidy
  email: "ywan0553@student.monash.edu"
  correspondingauthor: true
  qualifications: section1
- familyname: Xu
  othernames: Kexin
  address: Monash University
  email: "kxuu0029@student.monash.edu"
  qualifications: section2
  correspondingauthor: true
- familyname: Tang
  othernames: Ruiqi
  address: Monash University
  email: "rtan00062student.monash.edu"
  correspondingauthor: true
  qualifications: section3
department: Our consultancy \newline Yiru Wang &\newline Kexin XU &\newline Ruiqi Tang
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 8
    fig_width: 10
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
header-includes:
 \usepackage{float}
 \floatplacement{figure}{H}
 \floatplacement{table}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      eval = TRUE,
                      cache=TRUE, 
                      messages=FALSE, 
                      warning=FALSE)
```



```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries
library(tinytex)
library(gridExtra)
library(tidyverse)
library(readr)
library(bookdown)
library(knitr)
library(readxl)
library(haven)
```

\section*{State}

```{r NewSouthWales}
NewSouthWales <- read_excel("data/Victims_of_Crime_Extended_time_series.xls", sheet = 3,range = "A5:AB30")%>%
  pivot_longer(cols = '2010':'2019',  
               names_to = "Year",            
               values_to = "Count") %>%
  mutate(State = "NewSouthWales")%>%
  select(Offence,Year,Count,State)%>%
  filter(Offence %in%c("Murder","	
Attempted murder","Manslaughter","Sexual assault","Kidnapping/abduction","Armed robbery","	Unarmed robbery","Blackmail/extortion"))
```

```{r Victoria}
Victoria <- read_excel("data/Victims_of_Crime_Extended_time_series.xls", sheet = 4,range = "A5:AB28")%>%
  pivot_longer(cols = '2010':'2019',  
               names_to = "Year",            
               values_to = "Count") %>%
  mutate(State = "Victoria")%>%
  select(Offence,Year,Count,State)%>%
  filter(Offence %in%c("Murder","	
Attempted murder","Manslaughter","Sexual assault","Kidnapping/abduction","Armed robbery","	Unarmed robbery","Blackmail/extortion"))
```

```{r Queensland}
Queensland <- read_excel("data/Victims_of_Crime_Extended_time_series.xls", sheet = 5,range = "A5:AB28")%>%
  pivot_longer(cols = '2010':'2019',  
               names_to = "Year",            
               values_to = "Count") %>%
  mutate(State = "Queensland")%>%
  select(Offence,Year,Count,State)%>%
  filter(Offence %in%c("Murder","	
Attempted murder","Manslaughter","Sexual assault","Kidnapping/abduction","Armed robbery","	Unarmed robbery","Blackmail/extortion"))
```

```{r South_Australia}
South_Australia <- read_excel("data/Victims_of_Crime_Extended_time_series.xls", sheet = 6,range = "A5:AB30")%>%
  pivot_longer(cols = '2010':'2019',  
               names_to = "Year",            
               values_to = "Count") %>%
  mutate(State = "South Australia")%>%
  select(Offence,Year,Count,State)%>%
  filter(Offence %in%c("Murder","	
Attempted murder","Manslaughter","Sexual assault","Kidnapping/abduction","Armed robbery","	Unarmed robbery","Blackmail/extortion"))
```

```{r Western_Australia}
Western_Australia <- read_excel("data/Victims_of_Crime_Extended_time_series.xls", sheet = 7,range = "A5:AB30")%>%
  pivot_longer(cols = '2010':'2019',  
               names_to = "Year",            
               values_to = "Count") %>%
  mutate(State = "Western Australia")%>%
  select(Offence,Year,Count,State)%>%
  filter(Offence %in%c("Murder","	
Attempted murder","Manslaughter","Sexual assault","Kidnapping/abduction","Armed robbery","	Unarmed robbery","Blackmail/extortion"))
```

```{r Tasmania1}
Tasmania1 <- read_excel("data/Victims_of_Crime_Extended_time_series.xls", 
                       sheet = 8,range = "A5:AB22")%>%
  filter(Offence %in%c("Murder","	
Attempted murder","Manslaughter","Sexual assault","Kidnapping/abduction","Armed robbery","	Unarmed robbery","Blackmail/extortion"))%>%
  select(!("1993":"2009"))%>%
  pivot_longer(cols = '2010':'2013',  
               names_to = "Year",            
               values_to = "Count") %>%
  mutate(Count = as.double(Count))%>%
 mutate(State = "Tasmania")%>%
  select(Offence,Year,Count,State)
```

```{r Tasmania}
Tasmania2 <- read_excel("data/Victims_of_Crime_Extended_time_series.xls", 
                       sheet = 8,range = "A5:AB22")%>%
  filter(Offence %in%c("Murder","	
Attempted murder","Manslaughter","Sexual assault","Kidnapping/abduction","Armed robbery","	Unarmed robbery","Blackmail/extortion"))%>%
  select(!("1993":"2013"))%>%
  pivot_longer(cols = '2014':'2019',  
               names_to = "Year",            
               values_to = "Count") %>%
 mutate(State = "Tasmania")%>%
 select(Offence,Year,Count,State)
Tasmania <- bind_rows(Tasmania1,Tasmania2)
```



```{r Northern_Territory}
Northern_Territory <- read_excel("data/Victims_of_Crime_Extended_time_series.xls", sheet = 9,range = "A5:AB30")%>%
  pivot_longer(cols = '2010':'2019',  
               names_to = "Year",            
               values_to = "Count") %>%
  mutate(State = "Northern Territory")%>%
  select(Offence,Year,Count,State)%>%
  filter(Offence %in%c("Murder","	
Attempted murder","Manslaughter","Sexual assault","Kidnapping/abduction","Armed robbery","	Unarmed robbery","Blackmail/extortion"))
```

```{r Capital}
Capital <- read_excel("data/Victims_of_Crime_Extended_time_series.xls", sheet = 10,range = "A5:AB30")%>%
  pivot_longer(cols = '2010':'2019',  
               names_to = "Year",            
               values_to = "Count") %>%
  mutate(State = "Capital")%>%
  select(Offence,Year,Count,State)%>%
  filter(Offence %in%c("Murder","	
Attempted murder","Manslaughter","Sexual assault","Kidnapping/abduction","Armed robbery","	Unarmed robbery","Blackmail/extortion"))
```

```{r State}
State <- bind_rows(NewSouthWales,Victoria,Queensland,South_Australia,Western_Australia,Tasmania,Northern_Territory,Capital)
```


```{r plot1,fig.height = 8 , fig.width=10}
State %>%
  ggplot(aes(x = Offence,
             y = Count,
             fill = State))+
  geom_bar(stat = "identity",position = "dodge")+
  ggtitle("State") +
  facet_wrap(~Year, ncol = 1,scales= "free")
```



\section*{Gender}


\section*{Age}


